services:
  api:
    build:
      context: ./api
    container_name: api
    ports:
      - "8080:80"
    volumes:
      - ./api:/app
    env_file:
      - ".env"
  agent:
    build:
      context: ./agent
    container_name: agent
    ports:
      - "8081:80"
    volumes:
      - ./agent:/code
    env_file:
      - ".env"
  