from openai import OpenAI
import os
import json
from app.tools.registry import TOOL_REGISTRY
from app.tools.definitions import TOOLS

openai_api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI(
  api_key=openai_api_key
)

input_list = [
    {"role": "user", "content": "Can I get a new keyboard ? Also, what is my budget ? My id is 1"}
]

response = client.responses.create(
		model="gpt-4o-mini",
		instructions="You need to fill the text part with values from the input, if you are uncertain, keep null",
		input=input_list,
		text={
			"format": {
			"type": "json_schema",
			"name": "request_params",
			"strict": True,
			"schema": {
				"type": "object",
				"properties": {
					"user_id": {
						"type": ["number", "null"],
						"minimum": 0,
						"maximum": 130
					},
					"object": {
						"type": ["string", "null"],
						"minLength": 1
					},
					"purpose": {
						"type": ["string", "null"],
						"minLength": 1
					}
				},
				"required": ["user_id", "object", "purpose"],
				"additionalProperties": False
			}
		}
	}
)

input_list += response.output

print("Input before loop:")
print(input_list)
# while True:
# 	response = client.responses.create(
# 		model="gpt-4o-mini",
# 		instructions="test",
# 		input=input_list
# 	)

# response = client.responses.create(
#   model="gpt-4o-mini",
#   tools=TOOLS,
#   input=input_list
# #   stream=True
# )

# input_list += response.output

# print("Input before loop:")
# print(input_list)

# # for event in response:
# #     print(event)

# for item in response.output:
# 	if item.type == "function_call":
# 		tool_fn = TOOL_REGISTRY.get(item.name)
# 		if not tool_fn:
# 			raise ValueError(f"Incorrect tool call : {item.name}")
# 		arguments = json.loads(item.arguments)
# 		result = tool_fn(**arguments)
		
# 		input_list.append({
# 			"type": "function_call_output",
# 			"call_id": item.call_id,
# 			"output": json.dumps({
# 				"budget": result
# 			})
# 		})

# print("Final input:")
# print(input_list)

# response = client.responses.create(
#   model="gpt-4o-mini",
#   instructions="Respond only with the budget generated by a tool",
#   tools=TOOLS,
#   input=input_list
# )

# print("Final output:")
# print(response.model_dump_json(indent=2))
# print("\n" + response.output_text)
