from openai import OpenAI
import os
import json
from app.tools.inventory_tools.check_inventory import check_inventory
from app.tools.inventory_tools.registry import TOOL_REGISTRY
from app.tools.inventory_tools.definitions import TOOLS

openai_api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI(
  api_key=openai_api_key
)

request = {'user_id': 1, 'object_type': 'keyboard', 'purpose': 'broken'}

input_list = [
    {"role": "system", "content": f"You are an assistant that must answer this user request: {request}"}
]

response = client.responses.create(
    model="gpt-4o-mini",
	instructions=f"""You need to use your tools to check the current inventory. 
				You need to see if user's object type is available in the inventory. 
				The current request to use as an argument is in the input_list.""",
    tools=TOOLS,
    input=input_list
)

input_list += response.output
print(input_list)

for item in response.output:
    if item.type == "function_call":
        if item.name == "check_inventory":
            func = TOOL_REGISTRY.get(item.name)
            if not func:
                break #ici call erreur

            request = json.loads(item.arguments)["request"]
            inventory = func(request)
            
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": str(inventory),
            })

response = client.responses.create(
    model="gpt-4o-mini",
    instructions="""Check the current inventory generated by a tool, 
    then propose the objects to the user.
    Show the user only the name, price and availability""",
    input=input_list,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)