from openai import OpenAI
import os
import json
from app.tools.inventory_tools.check_inventory import check_inventory
from app.tools.inventory_tools.registry import TOOL_REGISTRY
from app.tools.inventory_tools.definitions import TOOLS

openai_api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI(
  api_key=openai_api_key
)

# request = {"user_id": 1, "object_type": "keyboard", "object_specs":"Wireless QWERTY"}

# object_type = "keyboard"
# object_specs = "Wireless QWERTY"

# input_list = [
#     {"role": "user", "content": f"Check the inventory for: {object_type}"}
# ]

def call_inventory_agent(object_type: str, object_specs: str):
	if not object_type:
		return {"error": "object_type is missing"}
	if not object_specs:
		return {"error": "object_specs is missing"}

	input_list = [
		{"role": "user", "content": f"Check the inventory for: {object_type}"}
	]

	response = client.responses.create(
		model="gpt-4o-mini",
		instructions="""You are an inventory checker agent.

		## Your only job:
		Call the check_inventory tool with the object type provided by the user.

		## After getting the result:
		- If objects are found: return them as a JSON array
		- If nothing is found: return an empty array []
		- Never make up results — only return what the tool gives you

		## Output format (always):
		{"found": true/false, "items": [...]}
		""",
		tools=TOOLS,
		input=input_list
	)

	input_list += response.output
	# print(response.output)
	# print(input_list)

	for item in response.output:
		if item.type == "function_call":
			func = TOOL_REGISTRY.get(item.name)
			parsed = json.loads(item.arguments)
			tool_result = func(**parsed)
			input_list.append({
				"type": "function_call_output",
				"call_id": item.call_id,
				"output": json.dumps(tool_result)
			})

			input_list.append({
				"role": "user",
				"content": f"""The user is looking for a {object_type} with these specs: {object_specs}.
				Rank the items above from best to worst match based on the specs.
				Return ONLY a raw JSON array, no markdown, no backticks, no preamble..
				Add a 'match_score' (0-10) and 'match_reason' field to each item."""
			})

			ranked_response = client.responses.create(
				model="gpt-4o-mini",
				instructions="You are an inventory ranking agent. Rank products by how well they match the user's specs. Never invent specs that are not in the item data.",
				input=input_list
			)
			# print(ranked_response)
			ranked_text = ranked_response.output[0].content[0].text
			
			return ranked_text

# input_list += response.output
# print(response.output)

# for item in response.output:
# 	if item.type == "function_call_output":
# 		response = item.output
# 		print(f'here is the resp : {response}')

# response = client.responses.create(
#     model="gpt-4o-mini",
#     instructions="""Check the current inventory generated by a tool, 
#     then propose the objects to the user.
#     Show the user only the name, price and availability""",
#     input=input_list,
# )

# # 5. The model should be able to give a response!
# print("Final output:")
# print(response.model_dump_json(indent=2))
# print("\n" + response.output_text)