
import json
from openai import OpenAI
from app.tools.purchase_tools.definitions import tools
from app.tools.purchase_tools.registry import TOOL_REGISTRY

op_client = OpenAI()

SYSTEM_PROMPT = """You are an Amazon product search agent.
					You will receive a product specifications and you must search for matching products, the products must have all the specifications.
					You must return ONLY a valid JSON object, no explanation, no markdown, no backticks.
					The JSON must follow this exact structure:
					{
						"found": boolean,
						"results": [
							{
								"name": string,
								"price": float,
								"link": string,
								"description": string,
								"thumbnail": string
							}
						]
					}
					Return maximum 3 results
					If no product with the exact specifications is found, return found : false and results : null in the structure
					if you receive an error send it back with the format 'error: explanation'."""

def call_amz_agent(data):
	input_list = [
		{
			"role" : "system",
			"content" : SYSTEM_PROMPT
		},
		{
			"role": "user",
			"content": str(data)
		}
	]

	try:
		response = op_client.responses.create(
			model = "gpt-4o-mini",
			tools = tools,
			input = input_list,
		)
	except Exception as e:
		return str(e)
	
	tool_was_called = any(item.type == "function_call" for item in response.output)
	if not tool_was_called:
		return {"found": False, "results": None, "error": "Model did not call the search tool"}

	input_list += response.output

	for item in response.output:
		if item.type == "function_call":
			func = TOOL_REGISTRY.get(item.name)
			if func is None:
				return {"found": False, "results": None, "error": f"Unknown tool: {item.name}"}
			product_info = json.loads(item.arguments)["product_info"]
			products = func(product_info)
			input_list.append({
				"type": "function_call_output",
				"call_id": item.call_id,
				"output": str(products),
			})

	try:
		response = op_client.responses.create(
			model= "gpt-4o-mini",
			instructions= "Respond using the products generated by tools\
							If no matching products with the exact specifications is found, return found : false and results : null in the structure\
							If you receive an error send it back with the format 'error: explanation'",
			tools= tools,
			input= input_list,
		)
	except Exception as e:
		return str(e)
	
	try:
		return json.loads(response.output_text)
	except json.JSONDecodeError:
		return {"found": False, "results": None, "error": "Invalid JSON returned by model"}


# data = {"object_type":"keyboard","object_specs":"apple Wireless AZERTY",  "budget": "400"}
# print(Call_amzAgent(data))
