
import json
from openai import OpenAI
from app.tools.purchase_tools.definitions import tools
from app.tools.purchase_tools.functions import get_product_info
from app.tools.purchase_tools.registry import TOOL_REGISTRY

op_client = OpenAI()

# cafe asin : B01N2KFHRS
budget = 80

# def get_amz_product(data):
data = {
	"product" : "coffee",
	"asin": "B01N2KFHRS",
	"reason": "i want a new coffee",
}
input_list = [
	{"role" : "user", "content" : f"Get me the price, the thumbnail and the link in string format to the amazon product using the asin in {data}, if you receive an error send it back with the format 'error: explanation'"}
]

response = op_client.responses.create(
	model = "gpt-4o-mini",
	tools = tools,
	input = input_list,
)
input_list += response.output

for item in response.output:
	if item.type == "function_call":
		func = TOOL_REGISTRY.get(item.name)
		asin = json.loads(item.arguments)["asin"]
		product = func(asin)
		input_list.append({
			"type": "function_call_output",
			"call_id": item.call_id,
			"output": product,
		})
	
response = op_client.responses.create(
	model= "gpt-4o-mini",
	instructions= "Respond with a price, link, and thumbnail link generated by tools, if you receive an error send it back with the format 'error: explanation'",
	tools= tools,
	input= input_list,
)

# print(response.model_dump_json(indent=2))
print("\n" + response.output_text)
