import os
import serpapi
import json
from openai import OpenAI
from app.tools.purchase_tools.definitions import tools

op_client = OpenAI()

# cafe asin : B01N2KFHRS
budget = 80

def get_product(asin):
	serp_client = serpapi.Client(api_key = os.getenv("SERPAPI_API_KEY"))
	try:
		results = serp_client.search({
			"engine" : "amazon",
			"k" : asin,
		})
	except Exception as e:
		return str(e)
	try:
		product = {
			"price": results["organic_results"][0]["price"],
			"link": results["organic_results"][0]["link"],
			"thumbnail": results["organic_results"][0]["thumbnail"]
		}
	except:
		return "Index error in 'results['organic_results'][0]'"
	return json.dumps(product)

# def get_amz_product(data):
data = {
	"product" : "coffee",
	"asin": "B01N2KFHRS",
	"reason": "i want a new coffee",
}
input_list = [
	{"role" : "user", "content" : f"Get me the price, the thumbnail and the link in string format to the amazon product using the asin in {data}, if you receive an error send it back with the format 'error: explanation'"}
]

response = op_client.responses.create(
	model = "gpt-4o-mini",
	tools = tools,
	input = input_list,
)
input_list += response.output

for item in response.output:
	if item.type == "function_call":
		if item.name == "get_product":
			asin = json.loads(item.arguments)["asin"]
			product = get_product(asin)
			input_list.append({
				"type": "function_call_output",
				"call_id": item.call_id,
				"output": product,
			})
	
response = op_client.responses.create(
	model= "gpt-4o-mini",
	instructions= "Respond with a price, link, and thumbnail link generated by tools, if you receive an error send it back with the format 'error: explanation'",
	tools= tools,
	input= input_list,
)

# print(response.model_dump_json(indent=2))
print("\n" + response.output_text)
