"""changed id from int to uuid in the Input_list table

Revision ID: 3a1cde08b801
Revises: 7426e2dc9c70
Create Date: 2026-05-01 05:40:39.430008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a1cde08b801'
down_revision: Union[str, Sequence[str], None] = '7426e2dc9c70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('input_list', 'id')
    op.add_column('input_list', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_primary_key('pk_input_list', 'input_list', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pk_input_list', 'input_list', type_='primary')
    op.drop_column('input_list', 'id')
    op.add_column('input_list', sa.Column('id', sa.INTEGER(), nullable=False))
    op.create_primary_key('pk_input_list', 'input_list', ['id'])
    # ### end Alembic commands ###
