"""adding chat table

Revision ID: 7426e2dc9c70
Revises: 4cb90b20f84b
Create Date: 2026-04-28 17:37:09.302275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7426e2dc9c70'
down_revision: Union[str, Sequence[str], None] = '4cb90b20f84b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Uuid(), nullable=False),
    sa.Column('sender', sa.Enum('user', 'agent', name='sender'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('tickets', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('users', sa.Column('hashed_password', sa.String(length=200), nullable=False))
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('users', 'hashed_password')
    op.alter_column('tickets', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    op.drop_table('chats')
    op.execute("DROP TYPE IF EXISTS sender")
    # ### end Alembic commands ###
