from openai import OpenAI
import os
import json
from app.tools.registry import TOOL_REGISTRY
from app.tools.definitions import TOOLS

openai_api_key = os.getenv("OPENAI_API_KEY")

client = OpenAI(
  api_key=openai_api_key
)

input_list = [
    {"role": "user", "content": "Can I get a new keyboard ?"}
]

parsed = {'user_id': None, 'object': None, 'purpose': None}

while True:
    response = client.responses.create(
        model="gpt-4o-mini",
        instructions=f"""You need to fill the text part with values from the input. 
						If you are uncertain, keep null. 
						This is the current state : {parsed}. 
						Do not change values that are not null""",
        input=input_list,
        text={"format": {"type": "json_schema", "name": "request_params", "strict": True, "schema": {
            "type": "object",
            "properties": {
                "user_id": {"type": ["number", "null"]},
                "object": {"type": ["string", "null"]},
                "purpose": {"type": ["string", "null"]}
            },
            "required": ["user_id", "object", "purpose"],
            "additionalProperties": False
        }}}
    )

    input_list += response.output
    print(f'response output : {response.output}')
    parsed = json.loads(response.output[0].content[0].text)
    print(f"Current state: {parsed}")

    if all(value is not None for value in parsed.values()):
        break

    # missing = [key for key, value in parsed.items() if value is None]
    missing = []
    for key,value in parsed.items():
        if value is None:
            missing.append(key)

    question_response = client.responses.create(
        model="gpt-4o-mini",
        instructions="You are a helpful assistant. Ask the user for the missing information in a natural, friendly way.",
        input=input_list + [
            {"role": "user", "content": f"The following fields are missing: {missing}. Ask the user for them."}
        ]
    )

    question = question_response.output[0].content[0].text
    print(f"Assistant: {question}")
    user_answer = input("You: ")

    input_list.append({"role": "user", "content": user_answer})

# tools = [
#     {
#         "type": "function",
#         "name": "check_policy",
#         "description": "Gives approval to buy the object requested ",
#         "parameters": {
#             "type": "object",
#             "properties": {
#                 "user_id": {
#                     "type": "number",
#                     "description": "An astrological sign like Taurus or Aquarius",
#                 },
#                 "object": {
#                     "type": "string",
#                     "description": "An astrological sign like Taurus or Aquarius",
#                 },
#                 "purpose": {
#                     "type": "string",
#                     "description": "An astrological sign like Taurus or Aquarius",
#                 },
#             },
#             "required": ["sign"],
#         },
#     },
# ]

# def get_horoscope(sign):
#     return f"{sign}: Next Tuesday you will befriend a baby otter."

# response = client.responses.create(
# 	model="gpt-4o-mini",
# 	tools=tools,
# 	instructions="You need to answer to the request based on your tools",
# 	input=input_list
# )

# input_list += response.output

# print("Input before loop:")
# print(input_list)

# for item in response.output:
# 	if item.type == "function_call":
# 		tool_fn = TOOL_REGISTRY.get(item.name)
# 		if not tool_fn:
# 			raise ValueError(f"Incorrect tool call : {item.name}")
# 		arguments = json.loads(item.arguments)
# 		result = tool_fn(**arguments)
		
# 		input_list.append({
# 			"type": "function_call_output",
# 			"call_id": item.call_id,
# 			"output": json.dumps({
# 				"res": result
# 			})
# 		})

# response = client.responses.create(
#   model="gpt-4o-mini",
#   instructions="Respond only with the outputs generated by tools, confirm to the user if the request had no problem",
#   tools=TOOLS,
#   input=input_list
# )

# print("Final output:")
# print(response.model_dump_json(indent=2))
# print("\n" + response.output_text)