from app.agents_app.openai_client import client
import json
from app.agents_app.tools.purchase_tools.definitions import tools
from app.agents_app.tools.purchase_tools.registry import TOOL_REGISTRY, PARAM_REGISTRY
from app.agents_app.tools.purchase_tools.functions import get_match_list
from app.agents_app.agents_exceptions import SubAgentError


SYSTEM_PROMPT = """You are an Amazon product search agent.
					You will receive a product specifications and you must search for matching products, the products must have all the specifications.
					You must return ONLY a valid JSON object, no explanation, no markdown, no backticks.
					The JSON must follow this exact structure:
					{
						"found": boolean,
						"results": [
							{
								"name": string,
								"price": string,
								"link": string,
								"description": string,
								"thumbnail": string
							}
						]
					}
					Return maximum 3 results
					If no product with the exact specifications is found, return found : false and results : null in the structure
					if you receive an error send it back with the format 'error: explanation'."""

async def call_amazon_agent(object_type: str, object_specs: str):
	data = {
		"object_type": object_type,
		"object_specs": object_specs,
	}
	input_list = [
		{
			"role" : "system",
			"content" : SYSTEM_PROMPT
		},
		{
			"role": "user",
			"content": json.dumps(data)
		}
	]

	try:
		response = await client.responses.create(
			model = "gpt-4o-mini",
			tools = tools,
			input = input_list,
		)
	except Exception as e:
		raise SubAgentError(
			message=str(e),
			agent= "amazon_agent",
			action= "Inform the user that there is a problem with the notifier agent, he can retry later",
			step="OpenAI call system call"
		)
	
	tool_was_called = any(item.type == "function_call" for item in response.output)
	if not tool_was_called:
		raise SubAgentError(
			message="Amazon agent did not call any tool",
			agent= "amazon_agent",
			action= "Inform the user that there is a problem with the notifier agent, he can retry later",
			step="tool_was_called"
		)

	input_list += response.output

	for item in response.output:
		if item.type == "function_call":
			if item.name == "get_amz_product_list":
				func = TOOL_REGISTRY.get(item.name)
				if func is None:
					raise SubAgentError(
						message="Amazon agent did not call any tool",
						agent= "amazon_agent",
						action= "Inform the user that there is a problem with the notifier agent, he can retry later",
						step="Tool call"
					)
				product = json.loads(item.arguments)[PARAM_REGISTRY.get(item.name)]
				result = await func(product)
				result = await get_match_list(data, result)
				input_list.append({
					"type": "function_call_output",
					"call_id": item.call_id,
					"output": str(result),
				})

	try:
		response = await client.responses.create(
			model= "gpt-4o-mini",
			instructions= "Respond using the products generated by tools\
							If you receive an error send it back with the format 'error: explanation'",
			tools= tools,
			input= input_list,
		)
	except Exception as e:
		raise SubAgentError(
			message=str(e),
			agent= "amazon_agent",
			action= "Inform the user that there is a problem with the notifier agent, he can retry later",
			step="OpenAI call products generated by tools"
		)
	
	try:
		return json.loads(response.output_text)
	except json.JSONDecodeError as e:
		raise SubAgentError(
			message=str(e),
			agent= "amazon_agent",
			action= "Inform the user that there is a problem with the notifier agent, he can retry later",
			step="json decode"
		)


# data = {"object_type":"keyboard","object_specs":"apple Wireless black",  "budget": "120"}
# print(call_amazon_agent("keyboard", "wireless"))
