import json, os
import aiosmtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from app.agents_app.openai_client import client
from app.database import AsyncSessionLocal

from sqlalchemy import update
from sqlalchemy.exc import SQLAlchemyError
from app.models.ticket_model import TicketStatus, Ticket, uuid

from app.agents_app.agents_exceptions import SubAgentError

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")

domain = ""

SYSTEM_PROMPT = """You are an email composition agent.
				You will receive a ticket context and must compose a professional acquisition request email to notify a manager.

				The email body must be valid HTML following this structure:
				1. Opening: "You have a new acquisition request from <strong>[employee name]</strong>."
				2. Request details: what the employee needs and the product details (name, source, link if available) — use a simple styled table or bullet list.
				3. Call to action: a styled button or link "Review request on the platform" pointing "https://housewares-staying-upc-beta.trycloudflare.com/requests".
				4. Closing: "<em>This request was automatically generated by the acquisition system.</em>"

				HTML style rules:
				- Use inline styles only
				- Font: font-family: Arial, sans-serif; color: #1a1a1a
				- Max width: 600px, centered
				- Button style: background:#4F46E5; color:white; padding:10px 20px; border-radius:6px; text-decoration:none
				- Add a thin top border in #4F46E5 at the top of the email for branding
				- Keep it clean and minimal

				Rules:
				- Tone must be professional but concise
				- Do not sign the email
				- Do not add pleasantries or filler sentences
				- You must return ONLY a valid JSON object, no explanation, no markdown, no backticks
				- The JSON must follow this exact structure:
				{
					"subject": string,
					"body": string
				}"""

async def update_ticket_status(ticket_id: str):
	async with AsyncSessionLocal() as db:
			try:
				stmt = await db.execute(
					update(Ticket)
					.where(Ticket.id == ticket_id)
					.values(status=TicketStatus.pending)
				)

				await db.commit()

			except SQLAlchemyError as e:
				await db.rollback()
				raise

async def send_email(to_send: str, subject: str, body: str):
	msg = MIMEMultipart()
	msg["From"] = SMTP_USER
	msg["To"] = to_send
	msg["Subject"] = subject
	msg.attach(MIMEText(body, "html"))

	try:
		await aiosmtplib.send(
			msg,
			hostname=SMTP_HOST,
			port=SMTP_PORT,
			username=SMTP_USER,
			password=SMTP_PASSWORD,
			start_tls=True
		)
		return True
	except Exception:
		raise
	

async def call_email_agent(data, product):
	final_data = data | product
	input_list = [
		{
			"role":"system",
			"content": SYSTEM_PROMPT,
		},
		{
			"role": "user",
			"content": json.dumps(final_data),
		}
	]

	try:
		response = await client.responses.create(
			model="gpt-4o-mini",
			input=input_list,
		)
	except Exception as e:
		raise SubAgentError(
				message=str(e),
				agent= "mail_agent",
				action= "Inform the user that there is a problem with the notifier agent, he can retry later",
				step="OpenAI call"
			)
	
	try:
		email_content = json.loads(response.output_text)
	except json.JSONDecodeError:
		raise SubAgentError(
			message="Invalid JSON returned by model",
			agent="mail_agent",
			action="your_action",
			step="json_parsing"
		)
	try:
		result = await send_email(data["manager"]["email"],
					 email_content["subject"],
					 email_content["body"])
	except Exception as e:
		raise SubAgentError(
			message=str(e),
			agent= "mail_agent",
			action= "Inform the user that there is a problem with the notifier agent, he can retry later",
			step="Email send"
		)
	
	if result is True:
		try:
			await update_ticket_status(data['ticket']['id'])
			return {"success": True, "to": data['manager']["email"]}
		except Exception as e:
			raise SubAgentError(
				message=str(e),
				agent= "mail_agent",
				action= "Inform the user that there is a problem with the notifier agent, he can retry later",
				step="update_ticket_status"
			)
	else:
		return {"success": False, "error": result}
